import { Brain, Cloud, Palette, BarChart3, Shield, Smartphone, Code, Database, Zap } from "lucide-react"

export interface Module {
  id: string
  title: string
  description: string
  duration: string
  difficulty: "Beginner" | "Intermediate" | "Advanced"
}

export interface Course {
  id: string
  slug: string
  title: string
  description: string
  icon: any
  level: string
  duration: string
  color: string
  gradient: string
  modules: Module[]
}

export const coursesData: Course[] = [
  {
    id: "1",
    slug: "ai-machine-learning",
    title: "AI & Machine Learning Mastery",
    description: "Master AI and ML with Python, TensorFlow, and real-world projects",
    icon: Brain,
    level: "Beginner to Advanced",
    duration: "12 weeks",
    color: "from-purple-500 to-purple-600",
    gradient: "from-purple-600 to-purple-900",
    modules: [
      {
        id: "ai-1",
        title: "Python for Data Science",
        description: "Learn NumPy, Pandas, and Matplotlib for data manipulation and visualization",
        duration: "6 hrs",
        difficulty: "Beginner",
      },
      {
        id: "ai-2",
        title: "Machine Learning Algorithms",
        description: "Regression, classification, clustering, and ensemble methods",
        duration: "10 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "ai-3",
        title: "Deep Learning with TensorFlow",
        description: "CNNs, RNNs, NLP basics, and neural network architectures",
        duration: "12 hrs",
        difficulty: "Advanced",
      },
      {
        id: "ai-4",
        title: "AI Projects",
        description: "Hands-on end-to-end projects with real datasets",
        duration: "8 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "ai-5",
        title: "Model Deployment",
        description: "Flask & FastAPI integrations for production deployment",
        duration: "6 hrs",
        difficulty: "Intermediate",
      },
    ],
  },
  {
    id: "2",
    slug: "devops-cloud",
    title: "DevOps & Cloud Engineering",
    description: "Master cloud infrastructure, containers, and CI/CD pipelines",
    icon: Cloud,
    level: "Beginner to Advanced",
    duration: "12 weeks",
    color: "from-blue-500 to-blue-600",
    gradient: "from-blue-600 to-blue-900",
    modules: [
      {
        id: "devops-1",
        title: "Linux Essentials",
        description: "Commands, permissions, shell scripting, and system administration",
        duration: "4 hrs",
        difficulty: "Beginner",
      },
      {
        id: "devops-2",
        title: "Docker & Containers",
        description: "Build, deploy, and manage containerized applications",
        duration: "6 hrs",
        difficulty: "Beginner",
      },
      {
        id: "devops-3",
        title: "Kubernetes for Beginners",
        description: "Manage scalable clusters and orchestrate containers",
        duration: "8 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "devops-4",
        title: "CI/CD Pipelines",
        description: "GitHub Actions, Jenkins, and automated deployment workflows",
        duration: "6 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "devops-5",
        title: "AWS Cloud Setup",
        description: "EC2, S3, Lambda functions, and cloud infrastructure",
        duration: "10 hrs",
        difficulty: "Advanced",
      },
    ],
  },
  {
    id: "3",
    slug: "ui-ux-design",
    title: "UI/UX Design Essentials",
    description: "Create beautiful, user-centered designs with Figma and design principles",
    icon: Palette,
    level: "Beginner to Advanced",
    duration: "10 weeks",
    color: "from-pink-500 to-pink-600",
    gradient: "from-pink-600 to-pink-900",
    modules: [
      {
        id: "uiux-1",
        title: "Figma Basics",
        description: "Frames, components, prototyping, and design systems",
        duration: "4 hrs",
        difficulty: "Beginner",
      },
      {
        id: "uiux-2",
        title: "Typography & Color Theory",
        description: "Visual hierarchy, contrast, and design principles",
        duration: "6 hrs",
        difficulty: "Beginner",
      },
      {
        id: "uiux-3",
        title: "Accessibility & UX Writing",
        description: "Inclusive design, clear communication, and user research",
        duration: "6 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "uiux-4",
        title: "Interactive Prototypes",
        description: "Advanced animations and interactive components in Figma",
        duration: "8 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "uiux-5",
        title: "Design Portfolio Project",
        description: "Showcase a real-world app design with case studies",
        duration: "10 hrs",
        difficulty: "Advanced",
      },
    ],
  },
  {
    id: "4",
    slug: "data-science",
    title: "Data Science & Analytics",
    description: "Transform data into insights with Python, visualization, and ML",
    icon: BarChart3,
    level: "Beginner to Advanced",
    duration: "12 weeks",
    color: "from-teal-500 to-teal-600",
    gradient: "from-teal-600 to-teal-900",
    modules: [
      {
        id: "data-1",
        title: "Python for Data Analysis",
        description: "Pandas, NumPy, and data manipulation techniques",
        duration: "6 hrs",
        difficulty: "Beginner",
      },
      {
        id: "data-2",
        title: "Statistics & Probability",
        description: "Hypothesis testing, distributions, and statistical inference",
        duration: "8 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "data-3",
        title: "Data Visualization",
        description: "Matplotlib, Seaborn, Plotly, and interactive dashboards",
        duration: "6 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "data-4",
        title: "Machine Learning with Scikit-learn",
        description: "Supervised and unsupervised learning models",
        duration: "10 hrs",
        difficulty: "Advanced",
      },
      {
        id: "data-5",
        title: "Data Projects",
        description: "Real-world analytics dashboards and data pipelines",
        duration: "10 hrs",
        difficulty: "Advanced",
      },
    ],
  },
  {
    id: "5",
    slug: "cybersecurity",
    title: "Cybersecurity Fundamentals",
    description: "Protect systems and applications with security best practices",
    icon: Shield,
    level: "Beginner to Advanced",
    duration: "12 weeks",
    color: "from-red-500 to-red-600",
    gradient: "from-red-600 to-red-900",
    modules: [
      {
        id: "cyber-1",
        title: "Networking Basics",
        description: "Protocols, IP addresses, firewalls, and network security",
        duration: "6 hrs",
        difficulty: "Beginner",
      },
      {
        id: "cyber-2",
        title: "Ethical Hacking",
        description: "Tools, penetration testing, and vulnerability assessment",
        duration: "8 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "cyber-3",
        title: "Security in Web Apps",
        description: "OWASP vulnerabilities, defense strategies, and secure coding",
        duration: "10 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "cyber-4",
        title: "Cryptography Basics",
        description: "Encryption, hashing, digital signatures, and key management",
        duration: "6 hrs",
        difficulty: "Advanced",
      },
      {
        id: "cyber-5",
        title: "Cyber Defense Project",
        description: "Secure a web app simulation and implement defense strategies",
        duration: "10 hrs",
        difficulty: "Advanced",
      },
    ],
  },
  {
    id: "6",
    slug: "mobile-app-dev",
    title: "Mobile App Development",
    description: "Build cross-platform mobile apps with Flutter and React Native",
    icon: Smartphone,
    level: "Beginner to Advanced",
    duration: "12 weeks",
    color: "from-orange-500 to-orange-600",
    gradient: "from-orange-600 to-orange-900",
    modules: [
      {
        id: "mobile-1",
        title: "Flutter Essentials",
        description: "Widgets, layouts, navigation, and state management",
        duration: "8 hrs",
        difficulty: "Beginner",
      },
      {
        id: "mobile-2",
        title: "React Native Basics",
        description: "Cross-platform mobile development with React",
        duration: "10 hrs",
        difficulty: "Beginner",
      },
      {
        id: "mobile-3",
        title: "Firebase Integration",
        description: "Authentication, real-time database, and cloud functions",
        duration: "6 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "mobile-4",
        title: "UI/UX for Mobile",
        description: "Responsive design, touch interactions, and user experience",
        duration: "8 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "mobile-5",
        title: "Mobile Project",
        description: "Publish a working app to app stores",
        duration: "10 hrs",
        difficulty: "Advanced",
      },
    ],
  },
  {
    id: "7",
    slug: "frontend-mastery",
    title: "Frontend Mastery",
    description: "Master modern frontend development with React, Next.js, and TypeScript",
    icon: Code,
    level: "Beginner to Advanced",
    duration: "14 weeks",
    color: "from-cyan-500 to-cyan-600",
    gradient: "from-cyan-600 to-cyan-900",
    modules: [
      {
        id: "frontend-1",
        title: "HTML & CSS Foundations",
        description: "Modern layouts, Flexbox, Grid, and responsive design",
        duration: "6 hrs",
        difficulty: "Beginner",
      },
      {
        id: "frontend-2",
        title: "JavaScript Deep Dive",
        description: "DOM manipulation, ES6+, async/await, and functional programming",
        duration: "8 hrs",
        difficulty: "Beginner",
      },
      {
        id: "frontend-3",
        title: "React.js Fundamentals",
        description: "Components, state, props, hooks, and lifecycle",
        duration: "10 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "frontend-4",
        title: "Next.js Advanced",
        description: "Server-side rendering, static generation, and routing",
        duration: "8 hrs",
        difficulty: "Advanced",
      },
      {
        id: "frontend-5",
        title: "Portfolio Project",
        description: "Build a professional frontend portfolio",
        duration: "12 hrs",
        difficulty: "Advanced",
      },
    ],
  },
  {
    id: "8",
    slug: "backend-fundamentals",
    title: "Backend Fundamentals",
    description: "Build scalable APIs and server applications with Node.js and databases",
    icon: Database,
    level: "Beginner to Advanced",
    duration: "12 weeks",
    color: "from-green-500 to-green-600",
    gradient: "from-green-600 to-green-900",
    modules: [
      {
        id: "backend-1",
        title: "Node.js Essentials",
        description: "Express, middleware, routing, and REST API development",
        duration: "8 hrs",
        difficulty: "Beginner",
      },
      {
        id: "backend-2",
        title: "Databases",
        description: "MongoDB and PostgreSQL design, queries, and optimization",
        duration: "10 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "backend-3",
        title: "Authentication",
        description: "JWT, sessions, OAuth, and security best practices",
        duration: "6 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "backend-4",
        title: "API Development",
        description: "CRUD operations, error handling, and validation",
        duration: "8 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "backend-5",
        title: "Server Deployment",
        description: "Deploy to Render, Railway, Vercel, and cloud platforms",
        duration: "6 hrs",
        difficulty: "Advanced",
      },
    ],
  },
  {
    id: "9",
    slug: "fullstack-excellence",
    title: "Full-Stack Excellence",
    description: "Build production-grade applications with MERN stack and best practices",
    icon: Zap,
    level: "Intermediate to Advanced",
    duration: "16 weeks",
    color: "from-purple-500 via-blue-500 to-purple-600",
    gradient: "from-purple-600 via-blue-600 to-purple-900",
    modules: [
      {
        id: "fullstack-1",
        title: "MERN Stack Integration",
        description: "React, Node.js, Express, and MongoDB integration",
        duration: "10 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "fullstack-2",
        title: "Authentication Systems",
        description: "Secure full-stack authentication and authorization",
        duration: "8 hrs",
        difficulty: "Intermediate",
      },
      {
        id: "fullstack-3",
        title: "Payment Gateway Integration",
        description: "Stripe and PayPal integration for e-commerce",
        duration: "6 hrs",
        difficulty: "Advanced",
      },
      {
        id: "fullstack-4",
        title: "Project Management",
        description: "Git workflows, deployment, CI/CD, and DevOps",
        duration: "8 hrs",
        difficulty: "Advanced",
      },
      {
        id: "fullstack-5",
        title: "Final Capstone Project",
        description: "Build a production-grade full-stack application",
        duration: "12 hrs",
        difficulty: "Advanced",
      },
    ],
  },
]
